.TH "src/modules/php_cgi Directory Reference" 3 "Sat Feb 29 2020" "Version 1.0" "Zia" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/modules/php_cgi Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBmain\&.cpp\fP"
.br
.ti -1c
.RI "file \fBphp_module\&.cpp\fP"
.br
.ti -1c
.RI "file \fBphp_module\&.hpp\fP"
.br
.ti -1c
.RI "file \fBtest\&.php\fP"
.br
.in -1c
