.TH "cfg::ConfigManager" 3 "Sat Feb 29 2020" "Version 1.0" "Zia" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cfg::ConfigManager \- \fBConfigManager\fP class to manage the configuration files\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ConfigManager\&.hpp>\fP
.SS "Public Types"

.in +1c
.ti -1c
.RI "using \fBCallbackHandler\fP = std::function< void()>"
.br
.RI "Callback handler that stores something's callback function\&. "
.ti -1c
.RI "using \fBThreadPtr\fP = std::shared_ptr< std::thread >"
.br
.RI "Thread pointer type, using shared_ptr as backend\&. "
.ti -1c
.RI "using \fBConfigList\fP = std::vector< \fBConfigPtr\fP >"
.br
.RI "Vector containing IConfig modules\&. "
.ti -1c
.RI "using \fBConfigMap\fP = std::unordered_map< std::string, \fBTimestamp\fP >"
.br
.RI "Unordered_map containing IConfig modules as key and config file timestamp\&. "
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBConfigManager\fP (const std::string &path)"
.br
.RI "Construct a new \fBConfigManager\fP object\&. "
.ti -1c
.RI "\fBConfigManager\fP ()"
.br
.RI "Construct a new \fBConfigManager\fP object\&. "
.ti -1c
.RI "virtual \fB~ConfigManager\fP ()=default"
.br
.RI "Destroy the \fBConfigManager\fP object\&. "
.ti -1c
.RI "void \fBmanage\fP ()"
.br
.RI "Set watching variable to true and run watch method in a detached thread\&. "
.ti -1c
.RI "void \fBstop\fP ()"
.br
.RI "Stop watch method and join the detached thread\&. "
.ti -1c
.RI "void \fBwatch\fP ()"
.br
.RI "Check every X milliseconds for a modification in the configuration path\&. "
.ti -1c
.RI "void \fBwatching\fP (const bool &watching)"
.br
.RI "Set watching attribute\&. "
.ti -1c
.RI "const bool \fBisWatching\fP () const noexcept"
.br
.RI "Get watching attribute\&. "
.ti -1c
.RI "void \fBloadConfigDir\fP (const std::string &path)"
.br
.RI "Load all configuration file from a given path\&. "
.ti -1c
.RI "void \fBonConfigChange\fP (\fBCallbackHandler\fP &&handler)"
.br
.RI "Callback called when a file has been modified\&. "
.ti -1c
.RI "void \fBonConfigErased\fP (\fBCallbackHandler\fP &&handler)"
.br
.RI "Callback called when a file has been erased\&. "
.ti -1c
.RI "void \fBsetConfigPath\fP (const std::string &path)"
.br
.RI "Set the configuration path\&. "
.ti -1c
.RI "const std::string \fBgetConfigPath\fP () const noexcept"
.br
.RI "Get the configuration path\&. "
.ti -1c
.RI "void \fBsetTimeToSleep\fP (const \fBTimeSleep\fP &timeSleep)"
.br
.RI "Set the time to sleep between each watch loop\&. "
.ti -1c
.RI "const \fBTimeSleep\fP \fBgetTimeToSleep\fP () const noexcept"
.br
.RI "Get the time to sleep between each watch loop\&. "
.ti -1c
.RI "\fBConfigPtr\fP \fBgetConfig\fP (const std::string &configName) const"
.br
.RI "Get \fBConfig\fP object from the loaded configs\&. "
.in -1c
.SH "Detailed Description"
.PP 
\fBConfigManager\fP class to manage the configuration files\&. 
.PP
Definition at line 28 of file ConfigManager\&.hpp\&.
.SH "Member Typedef Documentation"
.PP 
.SS "using \fBcfg::ConfigManager::CallbackHandler\fP =  std::function<void()>"

.PP
Callback handler that stores something's callback function\&. 
.PP
Definition at line 34 of file ConfigManager\&.hpp\&.
.SS "using \fBcfg::ConfigManager::ConfigList\fP =  std::vector<\fBConfigPtr\fP>"

.PP
Vector containing IConfig modules\&. 
.PP
Definition at line 44 of file ConfigManager\&.hpp\&.
.SS "using \fBcfg::ConfigManager::ConfigMap\fP =  std::unordered_map<std::string, \fBTimestamp\fP>"

.PP
Unordered_map containing IConfig modules as key and config file timestamp\&. 
.PP
Definition at line 49 of file ConfigManager\&.hpp\&.
.SS "using \fBcfg::ConfigManager::ThreadPtr\fP =  std::shared_ptr<std::thread>"

.PP
Thread pointer type, using shared_ptr as backend\&. 
.PP
Definition at line 39 of file ConfigManager\&.hpp\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ConfigManager::ConfigManager (const std::string & path)"

.PP
Construct a new \fBConfigManager\fP object\&. 
.PP
\fBParameters:\fP
.RS 4
\fIpath\fP Path to the directory containing configurations files to watch\&. 
.RE
.PP

.PP
Definition at line 12 of file ConfigManager\&.cpp\&.
.SS "ConfigManager::ConfigManager ()"

.PP
Construct a new \fBConfigManager\fP object\&. 
.PP
Definition at line 23 of file ConfigManager\&.cpp\&.
.SS "virtual cfg::ConfigManager::~ConfigManager ()\fC [virtual]\fP, \fC [default]\fP"

.PP
Destroy the \fBConfigManager\fP object\&. 
.SH "Member Function Documentation"
.PP 
.SS "\fBConfigPtr\fP ConfigManager::getConfig (const std::string & configName) const"

.PP
Get \fBConfig\fP object from the loaded configs\&. 
.PP
\fBParameters:\fP
.RS 4
\fIconfigName\fP Name of the \fBConfig\fP object wanted\&.
.RE
.PP
\fBReturns:\fP
.RS 4
Wanted ConfigPtr\&. 
.RE
.PP

.PP
Definition at line 126 of file ConfigManager\&.cpp\&.
.SS "const std::string ConfigManager::getConfigPath () const\fC [noexcept]\fP"

.PP
Get the configuration path\&. 
.PP
\fBReturns:\fP
.RS 4
The configuration path as a std::string\&. 
.RE
.PP

.PP
Definition at line 101 of file ConfigManager\&.cpp\&.
.SS "const \fBTimeSleep\fP ConfigManager::getTimeToSleep () const\fC [noexcept]\fP"

.PP
Get the time to sleep between each watch loop\&. 
.PP
\fBReturns:\fP
.RS 4
The time to sleep as a TimeSleep\&. 
.RE
.PP

.PP
Definition at line 111 of file ConfigManager\&.cpp\&.
.SS "const bool ConfigManager::isWatching () const\fC [noexcept]\fP"

.PP
Get watching attribute\&. 
.PP
\fBReturns:\fP
.RS 4
Watching attribute as a boolean\&. 
.RE
.PP

.PP
Definition at line 81 of file ConfigManager\&.cpp\&.
.SS "void ConfigManager::loadConfigDir (const std::string & path)"

.PP
Load all configuration file from a given path\&. 
.PP
\fBParameters:\fP
.RS 4
\fIpath\fP Path where to load the configuration files\&. 
.RE
.PP

.PP
Definition at line 86 of file ConfigManager\&.cpp\&.
.SS "void ConfigManager::manage ()"

.PP
Set watching variable to true and run watch method in a detached thread\&. 
.PP
Definition at line 34 of file ConfigManager\&.cpp\&.
.SS "void ConfigManager::onConfigChange (\fBCallbackHandler\fP && handler)"

.PP
Callback called when a file has been modified\&. 
.PP
\fBParameters:\fP
.RS 4
\fIhandler\fP Callback function\&. 
.RE
.PP

.PP
Definition at line 116 of file ConfigManager\&.cpp\&.
.SS "void ConfigManager::onConfigErased (\fBCallbackHandler\fP && handler)"

.PP
Callback called when a file has been erased\&. 
.PP
\fBParameters:\fP
.RS 4
\fIhandler\fP Callback function 
.RE
.PP

.PP
Definition at line 121 of file ConfigManager\&.cpp\&.
.SS "void ConfigManager::setConfigPath (const std::string & path)"

.PP
Set the configuration path\&. 
.PP
\fBParameters:\fP
.RS 4
\fIpath\fP Path where the configuration files are\&. 
.RE
.PP

.PP
Definition at line 96 of file ConfigManager\&.cpp\&.
.SS "void ConfigManager::setTimeToSleep (const \fBTimeSleep\fP & timeSleep)"

.PP
Set the time to sleep between each watch loop\&. 
.PP
\fBParameters:\fP
.RS 4
\fItimeSleep\fP Time to sleep in milliseconds\&. 
.RE
.PP

.PP
Definition at line 106 of file ConfigManager\&.cpp\&.
.SS "void ConfigManager::stop ()"

.PP
Stop watch method and join the detached thread\&. 
.PP
Definition at line 41 of file ConfigManager\&.cpp\&.
.SS "void ConfigManager::watch ()"

.PP
Check every X milliseconds for a modification in the configuration path\&. 
.IP "\(bu" 2
If a file is modified, matching config will be reloaded\&.
.IP "\(bu" 2
If a file is deleted, matching config will be removed from the ConfigList\&. 
.PP

.PP
Definition at line 47 of file ConfigManager\&.cpp\&.
.SS "void ConfigManager::watching (const bool & watching)"

.PP
Set watching attribute\&. 
.PP
\fBParameters:\fP
.RS 4
\fIwatching\fP Boolean\&. 
.RE
.PP

.PP
Definition at line 76 of file ConfigManager\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Zia from the source code\&.
