.TH "cfg::Config" 3 "Sat Feb 29 2020" "Version 1.0" "Zia" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cfg::Config \- \fBConfig\fP abstracts a configuration from a json file\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Config\&.hpp>\fP
.PP
Inherited by \fBZia::ServerConfig\fP\fC [virtual]\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBConfig\fP (const \fBFileDescriptor\fP &file, const std::string &name)"
.br
.RI "Construct a new \fBConfig\fP object\&. "
.ti -1c
.RI "virtual \fB~Config\fP ()=default"
.br
.RI "Destroy the \fBConfig\fP object\&. "
.ti -1c
.RI "void \fBloadConfig\fP (const std::filesystem::path &path)"
.br
.RI "Load configuration from a given file\&. "
.ti -1c
.RI "void \fBupdate\fP (const \fBFileStatus\fP &status)"
.br
.ti -1c
.RI "void \fBsetName\fP (const std::string &name)"
.br
.RI "Set the configuration's name\&. "
.ti -1c
.RI "const std::string \fBgetName\fP () const noexcept"
.br
.RI "Get the configuration's name\&. "
.ti -1c
.RI "const \fBFileDescriptor\fP \fBgetFileDescriptor\fP () const noexcept"
.br
.RI "Get the configuration's file descriptor\&. "
.ti -1c
.RI "void \fBsetPath\fP (const std::filesystem::path &path)"
.br
.RI "Set the configuration's file path\&. "
.ti -1c
.RI "std::filesystem::path \fBgetPath\fP () const noexcept"
.br
.RI "Get the configuration's file path\&. "
.ti -1c
.RI "void \fBsetTimestamp\fP (const \fBTimestamp\fP &timestamp)"
.br
.RI "Set the configuration's timestamp\&. "
.ti -1c
.RI "\fBTimestamp\fP \fBgetTimestamp\fP () const noexcept"
.br
.RI "Get the configuration's timestamp\&. "
.in -1c
.SH "Detailed Description"
.PP 
\fBConfig\fP abstracts a configuration from a json file\&. 
.PP
Definition at line 83 of file Config\&.hpp\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Config::Config (const \fBFileDescriptor\fP & file, const std::string & name)"

.PP
Construct a new \fBConfig\fP object\&. 
.PP
\fBParameters:\fP
.RS 4
\fIfile\fP File descriptor of the associated json configuration file\&. 
.br
\fIname\fP Registration name of the \fBConfig\fP object\&. 
.RE
.PP

.PP
Definition at line 12 of file Config\&.cpp\&.
.SS "virtual cfg::Config::~Config ()\fC [virtual]\fP, \fC [default]\fP"

.PP
Destroy the \fBConfig\fP object\&. 
.SH "Member Function Documentation"
.PP 
.SS "const \fBFileDescriptor\fP Config::getFileDescriptor () const\fC [noexcept]\fP"

.PP
Get the configuration's file descriptor\&. 
.PP
Definition at line 60 of file Config\&.cpp\&.
.SS "const std::string Config::getName () const\fC [noexcept]\fP"

.PP
Get the configuration's name\&. 
.PP
Definition at line 55 of file Config\&.cpp\&.
.SS "std::filesystem::path Config::getPath () const\fC [noexcept]\fP"

.PP
Get the configuration's file path\&. 
.PP
Definition at line 70 of file Config\&.cpp\&.
.SS "\fBTimestamp\fP Config::getTimestamp () const\fC [noexcept]\fP"

.PP
Get the configuration's timestamp\&. 
.PP
Definition at line 80 of file Config\&.cpp\&.
.SS "void Config::loadConfig (const std::filesystem::path & path)"

.PP
Load configuration from a given file\&. 
.PP
\fBParameters:\fP
.RS 4
\fIpath\fP Path to the configuration file\&. 
.RE
.PP

.PP
Definition at line 20 of file Config\&.cpp\&.
.SS "void Config::setName (const std::string & name)"

.PP
Set the configuration's name\&. 
.PP
\fBParameters:\fP
.RS 4
\fIname\fP Name to set\&. 
.RE
.PP

.PP
Definition at line 50 of file Config\&.cpp\&.
.SS "void Config::setPath (const std::filesystem::path & path)"

.PP
Set the configuration's file path\&. 
.PP
\fBParameters:\fP
.RS 4
\fIpath\fP Path to set\&. 
.RE
.PP

.PP
Definition at line 65 of file Config\&.cpp\&.
.SS "void Config::setTimestamp (const \fBTimestamp\fP & timestamp)"

.PP
Set the configuration's timestamp\&. 
.PP
\fBParameters:\fP
.RS 4
\fItimestamp\fP Timestamp to set\&. 
.RE
.PP

.PP
Definition at line 75 of file Config\&.cpp\&.
.SS "void Config::update (const \fBFileStatus\fP & status)"

.PP
Definition at line 35 of file Config\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Zia from the source code\&.
