.TH "src/config/Config.hpp" 3 "Sat Feb 29 2020" "Version 1.0" "Zia" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/config/Config.hpp
.SH SYNOPSIS
.br
.PP
\fC#include <filesystem>\fP
.br
\fC#include <fstream>\fP
.br
\fC#include <iostream>\fP
.br
\fC#include <nlohmann/json\&.hpp>\fP
.br
\fC#include <string>\fP
.br
\fC#include <thread>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBcfg::Config\fP"
.br
.RI "\fBConfig\fP abstracts a configuration from a json file\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBcfg\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "using \fBcfg::ConfigPtr\fP = std::shared_ptr< Config >"
.br
.RI "\fBConfig\fP pointer type, using shared_ptr as backend\&. "
.ti -1c
.RI "using \fBcfg::FileDescriptor\fP = std::filesystem::directory_entry"
.br
.RI "File descriptor from a directory entry\&. "
.ti -1c
.RI "using \fBcfg::Timestamp\fP = std::filesystem::file_time_type"
.br
.RI "File last modified date\&. "
.ti -1c
.RI "using \fBcfg::json\fP = nlohmann::json"
.br
.RI "Json library object\&. "
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBcfg::FileStatus\fP { \fBcfg::FileStatus::created\fP, \fBcfg::FileStatus::modified\fP, \fBcfg::FileStatus::erased\fP, \fBcfg::FileStatus::none\fP }
.RI "File status enumeration\&. ""
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Zia from the source code\&.
