.TH "src/server/Connection.hpp" 3 "Sat Feb 29 2020" "Version 1.0" "Zia" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/server/Connection.hpp
.SH SYNOPSIS
.br
.PP
\fC#include <array>\fP
.br
\fC#include <memory>\fP
.br
\fC#include <boost/asio\&.hpp>\fP
.br
\fC#include 'openZia/Pipeline\&.hpp'\fP
.br
\fC#include 'ConnectionManager\&.hpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBZia::Connection\fP"
.br
.RI "\fBConnection\fP class to manage the connection\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBZia\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Zia from the source code\&.
