.TH "src/server/ConnectionManager.hpp" 3 "Sat Feb 29 2020" "Version 1.0" "Zia" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/server/ConnectionManager.hpp
.SH SYNOPSIS
.br
.PP
\fC#include <set>\fP
.br
\fC#include 'Connection\&.hpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBZia::ConnectionManager\fP"
.br
.RI "\fBConnectionManager\fP class to manage the connection\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBZia\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef std::shared_ptr< \fBZia::Connection\fP > \fBConnectionPtr\fP"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef std::shared_ptr<\fBZia::Connection\fP> \fBConnectionPtr\fP"

.PP
Definition at line 19 of file ConnectionManager\&.hpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Zia from the source code\&.
