.TH "src/utils/EnvManager.hpp" 3 "Sat Feb 29 2020" "Version 1.0" "Zia" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/utils/EnvManager.hpp
.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include 'JsonLoader\&.hpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBtls::EnvManager\fP"
.br
.RI "\fBEnvManager\fP class to manage environment variables\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBtls\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Zia from the source code\&.
