.TH "FillModule" 3 "Sat Feb 29 2020" "Version 1.0" "Zia" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FillModule
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "std::map< std::string, std::string > \fBroutes_enums\fP"
.br
.RI "Enum for the routes\&. "
.ti -1c
.RI "std::map< std::string, std::string > \fBformats\fP"
.br
.RI "Enum for the formats\&. "
.in -1c
.SH "Variable Documentation"
.PP 
.SS "std::map<std::string, std::string> FillModule::formats"

.PP
Enum for the formats\&. 
.PP
Definition at line 92 of file FillPage\&.hpp\&.
.SS "std::map<std::string, std::string> FillModule::routes_enums"
\fBInitial value:\fP
.PP
.nf
= {
        {"/",       "index\&.html"},
        {"/test",   "index_test\&.html"},
        {"/php",    "index_php\&.html"},
        {"/form",   "index_form\&.html"},
        {"/carlos", "carlos\&.gif"},
        {"/cat",    "cat_choc\&.jpg"},
        {"/theo",   "theoWick\&.jpg"},
        {"/arthur", "arthurWick\&.jpg"}
    }
.fi
.PP
Enum for the routes\&. 
.PP
Definition at line 78 of file FillPage\&.hpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Zia from the source code\&.
