.TH "src/utils/JsonLoader.hpp" 3 "Sat Feb 29 2020" "Version 1.0" "Zia" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/utils/JsonLoader.hpp
.SH SYNOPSIS
.br
.PP
\fC#include <filesystem>\fP
.br
\fC#include <fstream>\fP
.br
\fC#include <iostream>\fP
.br
\fC#include <nlohmann/json\&.hpp>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBtls::JsonLoader\fP"
.br
.RI "\fBJsonLoader\fP class to manage a json file\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBtls\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "using \fBtls::json\fP = nlohmann::json"
.br
.RI "Json library object\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Zia from the source code\&.
