.TH "src/main.cpp" 3 "Sat Feb 29 2020" "Version 1.0" "Zia" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/main.cpp
.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include <exception>\fP
.br
\fC#include <server/Server\&.hpp>\fP
.br
\fC#include <utils/EnvManager\&.hpp>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (int argc, char *argv[])"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main (int argc, char * argv[])"

.PP
Definition at line 33 of file main\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Zia from the source code\&.
