.TH "src/server/Module.hpp" 3 "Sat Feb 29 2020" "Version 1.0" "Zia" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/server/Module.hpp
.SH SYNOPSIS
.br
.PP
\fC#include <config/Config\&.hpp>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBZia::Module\fP"
.br
.RI "\fBModule\fP class to manage the modules\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBZia\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Zia from the source code\&.
