.TH "ParserModule" 3 "Sat Feb 29 2020" "Version 1.0" "Zia" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ParserModule
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "const std::vector< std::string > \fBmethods\fP"
.br
.RI "Enum for the HTTP methods\&. "
.ti -1c
.RI "std::map< std::string, oZ::HTTP::Method > \fBmethods_enums\fP"
.br
.RI "Enum between HTTP method and the api definds\&. "
.in -1c
.SH "Variable Documentation"
.PP 
.SS "const std::vector<std::string> ParserModule::methods"
\fBInitial value:\fP
.PP
.nf
= {
        "GET",
        "HEAD",
        "POST",
        "PUT",
        "DELETE",
        "CONNECT",
        "OPTIONS",
        "TRACE"
    }
.fi
.PP
Enum for the HTTP methods\&. 
.PP
Definition at line 19 of file ParserModule\&.hpp\&.
.SS "std::map<std::string, oZ::HTTP::Method> ParserModule::methods_enums"
\fBInitial value:\fP
.PP
.nf
= {
        {"GET",     oZ::HTTP::Method::Get},
        {"HEAD",    oZ::HTTP::Method::Head},
        {"POST",    oZ::HTTP::Method::Post},
        {"PUT",     oZ::HTTP::Method::Put},
        {"DELETE",  oZ::HTTP::Method::Delete},
        {"CONNECT", oZ::HTTP::Method::Connect},
        {"OPTIONS", oZ::HTTP::Method::Option},
        {"TRACE",   oZ::HTTP::Method::Trace}
    }
.fi
.PP
Enum between HTTP method and the api definds\&. 
.PP
Definition at line 33 of file ParserModule\&.hpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Zia from the source code\&.
