.TH "Parser" 3 "Sat Feb 29 2020" "Version 1.0" "Zia" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Parser \- \fBParser\fP class to manage the parser module\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ParserModule\&.hpp>\fP
.PP
Inherits IModule\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBParser\fP ()=default"
.br
.RI "Default constructor for the parset module\&. "
.ti -1c
.RI "virtual const char * \fBgetName\fP (void) const"
.br
.RI "Get the name of the module\&. "
.ti -1c
.RI "virtual void \fBonRegisterCallbacks\fP (oZ::Pipeline &pipeline)"
.br
.RI "Fct for the pipeline (load in the right place in the right position) "
.in -1c
.SH "Detailed Description"
.PP 
\fBParser\fP class to manage the parser module\&. 
.PP
Definition at line 48 of file ParserModule\&.hpp\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Parser::Parser ()\fC [default]\fP"

.PP
Default constructor for the parset module\&. 
.SH "Member Function Documentation"
.PP 
.SS "virtual const char* Parser::getName (void) const\fC [inline]\fP, \fC [virtual]\fP"

.PP
Get the name of the module\&. 
.PP
\fBReturns:\fP
.RS 4
The name of the module 
.RE
.PP

.PP
Definition at line 60 of file ParserModule\&.hpp\&.
.SS "void Parser::onRegisterCallbacks (oZ::Pipeline & pipeline)\fC [virtual]\fP"

.PP
Fct for the pipeline (load in the right place in the right position) 
.PP
\fBParameters:\fP
.RS 4
\fIpipeline\fP Reference on the pipeline where the module is load 
.RE
.PP

.PP
Definition at line 15 of file ParserModule\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Zia from the source code\&.
