.TH "src/modules/parser/ParserModule.hpp" 3 "Sat Feb 29 2020" "Version 1.0" "Zia" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/modules/parser/ParserModule.hpp
.SH SYNOPSIS
.br
.PP
\fC#include <openZia/IModule\&.hpp>\fP
.br
\fC#include <openZia/Pipeline\&.hpp>\fP
.br
\fC#include <map>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBParser\fP"
.br
.RI "\fBParser\fP class to manage the parser module\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBParserModule\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "const std::vector< std::string > \fBParserModule::methods\fP"
.br
.RI "Enum for the HTTP methods\&. "
.ti -1c
.RI "std::map< std::string, oZ::HTTP::Method > \fBParserModule::methods_enums\fP"
.br
.RI "Enum between HTTP method and the api definds\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Zia from the source code\&.
