.TH "src/modules/php_cgi/php_module.hpp" 3 "Sat Feb 29 2020" "Version 1.0" "Zia" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/modules/php_cgi/php_module.hpp
.SH SYNOPSIS
.br
.PP
\fC#include <openZia/IModule\&.hpp>\fP
.br
\fC#include <openZia/Pipeline\&.hpp>\fP
.br
\fC#include <stdio\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <unistd\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br
\fC#include <sys/wait\&.h>\fP
.br
\fC#include <sys/types\&.h>\fP
.br
\fC#include <iostream>\fP
.br
\fC#include <fstream>\fP
.br
\fC#include <map>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBPHP_CGI\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBPHPModule\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBHTML_FILES_POSI\fP   'src/HTML/'"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "std::map< std::string, std::string > \fBPHPModule::routes_enums\fP"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define HTML_FILES_POSI   'src/HTML/'"

.PP
Definition at line 22 of file php_module\&.hpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Zia from the source code\&.
