.TH "PHP_CGI" 3 "Sat Feb 29 2020" "Version 1.0" "Zia" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PHP_CGI \- \fBPHP_CGI\fP class to manage the PHP module\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <PHPModule\&.hpp>\fP
.PP
Inherits IModule\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPHP_CGI\fP ()=default"
.br
.RI "Default constructor for the php module\&. "
.ti -1c
.RI "virtual const char * \fBgetName\fP (void) const"
.br
.RI "Get the name of the module\&. "
.ti -1c
.RI "virtual void \fBonRegisterCallbacks\fP (oZ::Pipeline &pipeline)"
.br
.RI "Fct for the pipeline (load in the right place in the right position) "
.in -1c
.SH "Detailed Description"
.PP 
\fBPHP_CGI\fP class to manage the PHP module\&. 
.PP
Definition at line 40 of file PHPModule\&.hpp\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "PHP_CGI::PHP_CGI ()\fC [default]\fP"

.PP
Default constructor for the php module\&. 
.SH "Member Function Documentation"
.PP 
.SS "virtual const char* PHP_CGI::getName (void) const\fC [inline]\fP, \fC [virtual]\fP"

.PP
Get the name of the module\&. 
.PP
\fBReturns:\fP
.RS 4
The name of the module 
.RE
.PP

.PP
Definition at line 53 of file PHPModule\&.hpp\&.
.SS "void PHP_CGI::onRegisterCallbacks (oZ::Pipeline & pipeline)\fC [virtual]\fP"

.PP
Fct for the pipeline (load in the right place in the right position) 
.PP
\fBParameters:\fP
.RS 4
\fIpipeline\fP Reference on the pipeline where the module is load 
.RE
.PP

.PP
Definition at line 14 of file PHPModule\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Zia from the source code\&.
