.TH "PHPModule" 3 "Sat Feb 29 2020" "Version 1.0" "Zia" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PHPModule
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "std::map< std::string, std::string > \fBroutes_enums\fP"
.br
.RI "Enum for the server's routes with php\&. "
.in -1c
.SH "Variable Documentation"
.PP 
.SS "std::map<std::string, std::string> PHPModule::routes_enums"
\fBInitial value:\fP
.PP
.nf
= {
        {"/",      "index\&.html"},
        {"/test",  "index_test\&.html"},
        {"/php",   "index_php\&.html"},
        {"/form",  "index_form\&.html"}
    }
.fi
.PP
Enum for the server's routes with php\&. 
.PP
Definition at line 29 of file PHPModule\&.hpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Zia from the source code\&.
