.TH "src/server/ServerConfig.hpp" 3 "Sat Feb 29 2020" "Version 1.0" "Zia" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/server/ServerConfig.hpp
.SH SYNOPSIS
.br
.PP
\fC#include <set>\fP
.br
\fC#include <vector>\fP
.br
\fC#include <config/Config\&.hpp>\fP
.br
\fC#include <openZia/IModule\&.hpp>\fP
.br
\fC#include <utils/EnvManager\&.hpp>\fP
.br
\fC#include <utils/JsonLoader\&.hpp>\fP
.br
\fC#include 'Module\&.hpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBZia::ServerConfig\fP"
.br
.RI "\fBServerConfig\fP class to manage configuration files of the server\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBZia\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "using \fBZia::ModulePtr\fP = std::shared_ptr< Module >"
.br
.RI "\fBModule\fP pointer type, using shared_ptr as backend\&. "
.ti -1c
.RI "using \fBZia::EnabledList\fP = std::set< ModulePtr >"
.br
.RI "Set containing ModulePtr modules\&. "
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "const int \fBZia::DefaultPort\fP = 80"
.br
.RI "Default HTTP port\&. "
.ti -1c
.RI "const int \fBZia::DefaultPortHTTPS\fP = 443"
.br
.RI "Default HTTPS port\&. "
.ti -1c
.RI "const std::string \fBZia::DefaultIP\fP = '127\&.0\&.0\&.1'"
.br
.RI "Default IP address\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Zia from the source code\&.
