.TH "SharedMemory" 3 "Sat Feb 29 2020" "Version 1.0" "Zia" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SharedMemory
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SharedMemory\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSharedMemory\fP ()=default"
.br
.ti -1c
.RI "\fB~SharedMemory\fP ()=default"
.br
.ti -1c
.RI "void \fBwrite_data\fP (key_t, size_t, size_t, std::string)"
.br
.ti -1c
.RI "char * \fBget_data\fP (key_t, size_t, size_t) const"
.br
.ti -1c
.RI "char * \fBget_data_by_id\fP (int) const"
.br
.ti -1c
.RI "void \fBdetach_from\fP (const void *)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBdestroy\fP (int, int)"
.br
.ti -1c
.RI "static key_t \fBkey_gen\fP (std::string, int)"
.br
.ti -1c
.RI "static int \fBid_gen\fP (key_t, size_t, size_t)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 18 of file SharedMemory\&.hpp\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "SharedMemory::SharedMemory ()\fC [default]\fP"

.SS "SharedMemory::~SharedMemory ()\fC [default]\fP"

.SH "Member Function Documentation"
.PP 
.SS "void SharedMemory::destroy (int shmId, int process)\fC [static]\fP"

.PP
Definition at line 43 of file SharedMemory\&.cpp\&.
.SS "void SharedMemory::detach_from (const void * data)"

.PP
Definition at line 37 of file SharedMemory\&.cpp\&.
.SS "char * SharedMemory::get_data (key_t key, size_t data_size, size_t process) const"

.PP
Definition at line 20 of file SharedMemory\&.cpp\&.
.SS "char * SharedMemory::get_data_by_id (int shmId) const"

.PP
Definition at line 28 of file SharedMemory\&.cpp\&.
.SS "int SharedMemory::id_gen (key_t key, size_t data_size, size_t process)\fC [static]\fP"

.PP
Definition at line 54 of file SharedMemory\&.cpp\&.
.SS "key_t SharedMemory::key_gen (std::string pathname, int proj_id)\fC [static]\fP"

.PP
Definition at line 49 of file SharedMemory\&.cpp\&.
.SS "void SharedMemory::write_data (key_t key, size_t data_size, size_t process, std::string data)"

.PP
Definition at line 11 of file SharedMemory\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Zia from the source code\&.
