.TH "src/utils/SharedMemory.hpp" 3 "Sat Feb 29 2020" "Version 1.0" "Zia" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/utils/SharedMemory.hpp
.SH SYNOPSIS
.br
.PP
\fC#include <list>\fP
.br
\fC#include <stdio\&.h>\fP
.br
\fC#include <string>\fP
.br
\fC#include <sys/ipc\&.h>\fP
.br
\fC#include <sys/shm\&.h>\fP
.br
\fC#include <sys/types\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBSharedMemory\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Zia from the source code\&.
