.TH "src/modules/SSL/SSLModule.hpp" 3 "Sat Feb 29 2020" "Version 1.0" "Zia" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/modules/SSL/SSLModule.hpp
.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include <unistd\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br
\fC#include <sys/socket\&.h>\fP
.br
\fC#include <arpa/inet\&.h>\fP
.br
\fC#include <openssl/ssl\&.h>\fP
.br
\fC#include <openssl/err\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <iostream>\fP
.br
\fC#include <openZia/IModule\&.hpp>\fP
.br
\fC#include <openZia/Pipeline\&.hpp>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBSSLModule\fP"
.br
.RI "\fBSSLModule\fP class to manage the SSL module\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Zia from the source code\&.
