.TH "SSLModule" 3 "Sat Feb 29 2020" "Version 1.0" "Zia" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SSLModule \- \fBSSLModule\fP class to manage the SSL module\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SSLModule\&.hpp>\fP
.PP
Inherits IModule\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSSLModule\fP ()=default"
.br
.RI "Default constructor for the ssl module\&. "
.ti -1c
.RI "\fB~SSLModule\fP ()"
.br
.RI "Default destructor for the php module\&. "
.ti -1c
.RI "virtual const char * \fBgetName\fP (void) const"
.br
.RI "Get the name of the module\&. "
.ti -1c
.RI "virtual void \fBonRegisterCallbacks\fP (oZ::Pipeline &pipeline)"
.br
.RI "Fct for the pipeline (load in the right place in the right position) "
.ti -1c
.RI "virtual void \fBonLoadConfigurationFile\fP (const std::string &conf)"
.br
.RI "Load the conf for the pipeline\&. "
.ti -1c
.RI "virtual void \fBonConnection\fP (const oZ::FileDescriptor fd, const oZ::Endpoint endpoint, const bool useEncryption)"
.br
.RI "Init the ssl lib\&. "
.ti -1c
.RI "virtual void \fBonDisconnection\fP (const oZ::FileDescriptor fd, const oZ::Endpoint endpoint)"
.br
.RI "Destroy the ssl lib\&. "
.in -1c
.SH "Detailed Description"
.PP 
\fBSSLModule\fP class to manage the SSL module\&. 
.PP
Definition at line 26 of file SSLModule\&.hpp\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "SSLModule::SSLModule ()\fC [default]\fP"

.PP
Default constructor for the ssl module\&. 
.SS "SSLModule::~SSLModule ()"

.PP
Default destructor for the php module\&. 
.PP
Definition at line 12 of file SSLModule\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "virtual const char* SSLModule::getName (void) const\fC [inline]\fP, \fC [virtual]\fP"

.PP
Get the name of the module\&. 
.PP
\fBReturns:\fP
.RS 4
The name of the module 
.RE
.PP

.PP
Definition at line 44 of file SSLModule\&.hpp\&.
.SS "void SSLModule::onConnection (const oZ::FileDescriptor fd, const oZ::Endpoint endpoint, const bool useEncryption)\fC [virtual]\fP"

.PP
Init the ssl lib\&. 
.PP
\fBParameters:\fP
.RS 4
\fIfd\fP Fd open for the listen 
.br
\fIendpoint\fP Endpoint use for the listen 
.br
\fIuseEncryption\fP Bool to know if it's HTTP or HTTPS 
.RE
.PP

.PP
Definition at line 35 of file SSLModule\&.cpp\&.
.SS "void SSLModule::onDisconnection (const oZ::FileDescriptor fd, const oZ::Endpoint endpoint)\fC [virtual]\fP"

.PP
Destroy the ssl lib\&. 
.PP
\fBParameters:\fP
.RS 4
\fIfd\fP Fd close after the listen 
.br
\fIendpoint\fP Endpoint close after the listen 
.RE
.PP

.PP
Definition at line 52 of file SSLModule\&.cpp\&.
.SS "void SSLModule::onLoadConfigurationFile (const std::string & conf)\fC [virtual]\fP"

.PP
Load the conf for the pipeline\&. 
.PP
\fBParameters:\fP
.RS 4
\fIconf\fP Conf for modif the pipeline 
.RE
.PP

.PP
Definition at line 58 of file SSLModule\&.cpp\&.
.SS "void SSLModule::onRegisterCallbacks (oZ::Pipeline & pipeline)\fC [virtual]\fP"

.PP
Fct for the pipeline (load in the right place in the right position) 
.PP
\fBParameters:\fP
.RS 4
\fIpipeline\fP Reference on the pipeline where the module is load 
.RE
.PP

.PP
Definition at line 20 of file SSLModule\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Zia from the source code\&.
