.TH "src/modules/php_cgi/test.php" 3 "Sat Feb 29 2020" "Version 1.0" "Zia" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/modules/php_cgi/test.php
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBwow\fP ()"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "wow ()"

.PP
Definition at line 3 of file test\&.php\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Zia from the source code\&.
