.TH "tls" 3 "Sat Feb 29 2020" "Version 1.0" "Zia" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tls
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBEnvManager\fP"
.br
.RI "\fBEnvManager\fP class to manage environment variables\&. "
.ti -1c
.RI "class \fBJsonLoader\fP"
.br
.RI "\fBJsonLoader\fP class to manage a json file\&. "
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "using \fBjson\fP = nlohmann::json"
.br
.RI "Json library object\&. "
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "using \fBtls::json\fP = typedef nlohmann::json"

.PP
Json library object\&. 
.PP
Definition at line 20 of file JsonLoader\&.hpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Zia from the source code\&.
