.TH "tls::EnvManager" 3 "Sat Feb 29 2020" "Version 1.0" "Zia" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tls::EnvManager \- \fBEnvManager\fP class to manage environment variables\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <EnvManager\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBEnvManager\fP ()"
.br
.RI "Construct a new \fBEnvManager\fP object\&. "
.ti -1c
.RI "\fBEnvManager\fP (const std::filesystem::path &config_path)"
.br
.RI "Construct a new \fBEnvManager\fP object\&. "
.ti -1c
.RI "\fB~EnvManager\fP ()=default"
.br
.RI "Destroy the \fBEnvManager\fP object\&. "
.ti -1c
.RI "void \fBloadEnv\fP (const std::filesystem::path &config_path='')"
.br
.RI "Set a list of environment variable from a json file\&. "
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBsetEnv\fP (const std::string &name, const std::string &value)"
.br
.RI "Set an environment variable\&. "
.ti -1c
.RI "static const std::string \fBgetEnv\fP (const std::string &name)"
.br
.RI "Get an environment variable\&. "
.in -1c
.SH "Detailed Description"
.PP 
\fBEnvManager\fP class to manage environment variables\&. 
.PP
Definition at line 19 of file EnvManager\&.hpp\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "EnvManager::EnvManager ()"

.PP
Construct a new \fBEnvManager\fP object\&. 
.PP
Definition at line 12 of file EnvManager\&.cpp\&.
.SS "EnvManager::EnvManager (const std::filesystem::path & config_path)"

.PP
Construct a new \fBEnvManager\fP object\&. 
.PP
\fBParameters:\fP
.RS 4
\fIconfig_path\fP Path to a json configuration file\&. 
.RE
.PP

.PP
Definition at line 18 of file EnvManager\&.cpp\&.
.SS "tls::EnvManager::~EnvManager ()\fC [default]\fP"

.PP
Destroy the \fBEnvManager\fP object\&. 
.SH "Member Function Documentation"
.PP 
.SS "const std::string EnvManager::getEnv (const std::string & name)\fC [static]\fP"

.PP
Get an environment variable\&. 
.PP
\fBParameters:\fP
.RS 4
\fIname\fP Name of the variable to retrieve\&.
.RE
.PP
\fBReturns:\fP
.RS 4
Value of the found environment variable\&. 
.RE
.PP

.PP
Definition at line 31 of file EnvManager\&.cpp\&.
.SS "void EnvManager::loadEnv (const std::filesystem::path & config_path = \fC''\fP)"

.PP
Set a list of environment variable from a json file\&. 
.PP
\fBParameters:\fP
.RS 4
\fIconfig_path\fP File where the environment variables are described\&. 
.RE
.PP

.PP
Definition at line 41 of file EnvManager\&.cpp\&.
.SS "void EnvManager::setEnv (const std::string & name, const std::string & value)\fC [static]\fP"

.PP
Set an environment variable\&. 
.PP
\fBParameters:\fP
.RS 4
\fIname\fP Name of the variable\&. 
.br
\fIvalue\fP Value of the variable\&. 
.RE
.PP

.PP
Definition at line 25 of file EnvManager\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Zia from the source code\&.
