.TH "Zia::ServerConfig" 3 "Sat Feb 29 2020" "Version 1.0" "Zia" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Zia::ServerConfig \- \fBServerConfig\fP class to manage configuration files of the server\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ServerConfig\&.hpp>\fP
.PP
Inherits \fBcfg::Config\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBServerConfig\fP (const \fBFileDescriptor\fP &file, const std::string &name)"
.br
.RI "Construct a new \fBServerConfig\fP object\&. "
.ti -1c
.RI "\fB~ServerConfig\fP ()=default"
.br
.RI "Destroy the \fBServerConfig\fP object\&. "
.ti -1c
.RI "void \fBloadConfig\fP (const std::filesystem::path &path)"
.br
.RI "Load configuration from a given file\&. "
.ti -1c
.RI "void \fBupdateEnabledModulesList\fP ()"
.br
.RI "Update list of enabled modules\&. "
.ti -1c
.RI "const std::string \fBgetAddress\fP () const noexcept"
.br
.ti -1c
.RI "const int \fBgetPort\fP () const noexcept"
.br
.ti -1c
.RI "std::string \fBgetConfigPath\fP () const noexcept"
.br
.ti -1c
.RI "std::string \fBgetModulesPath\fP () const noexcept"
.br
.ti -1c
.RI "const \fBEnabledList\fP \fBgetEnabledModulesList\fP () const noexcept"
.br
.RI "Get list of enabled modules\&. "
.ti -1c
.RI "const std::string \fBgetModuleName\fP (const std::string &filename) const"
.br
.ti -1c
.RI "const std::string \fBgetModuleName\fP (const \fBFileDescriptor\fP &file) const"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBServerConfig\fP class to manage configuration files of the server\&. 
.PP
Definition at line 52 of file ServerConfig\&.hpp\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ServerConfig::ServerConfig (const \fBFileDescriptor\fP & file, const std::string & name)"

.PP
Construct a new \fBServerConfig\fP object\&. 
.PP
\fBParameters:\fP
.RS 4
\fIfile\fP File descriptor of the associated json configuration file\&. 
.br
\fIname\fP Registration name of the \fBServerConfig\fP object\&. 
.RE
.PP

.PP
Definition at line 12 of file ServerConfig\&.cpp\&.
.SS "Zia::ServerConfig::~ServerConfig ()\fC [default]\fP"

.PP
Destroy the \fBServerConfig\fP object\&. 
.SH "Member Function Documentation"
.PP 
.SS "const std::string ServerConfig::getAddress () const\fC [noexcept]\fP"

.PP
Definition at line 54 of file ServerConfig\&.cpp\&.
.SS "std::string ServerConfig::getConfigPath () const\fC [noexcept]\fP"

.PP
Definition at line 64 of file ServerConfig\&.cpp\&.
.SS "const \fBEnabledList\fP ServerConfig::getEnabledModulesList () const\fC [noexcept]\fP"

.PP
Get list of enabled modules\&. 
.PP
\fBReturns:\fP
.RS 4
List of enabled modules as EnabledList type\&. 
.RE
.PP

.PP
Definition at line 74 of file ServerConfig\&.cpp\&.
.SS "const std::string ServerConfig::getModuleName (const std::string & filename) const"

.PP
Definition at line 79 of file ServerConfig\&.cpp\&.
.SS "const std::string ServerConfig::getModuleName (const \fBFileDescriptor\fP & file) const"

.PP
Definition at line 86 of file ServerConfig\&.cpp\&.
.SS "std::string ServerConfig::getModulesPath () const\fC [noexcept]\fP"

.PP
Definition at line 69 of file ServerConfig\&.cpp\&.
.SS "const int ServerConfig::getPort () const\fC [noexcept]\fP"

.PP
Definition at line 59 of file ServerConfig\&.cpp\&.
.SS "void ServerConfig::loadConfig (const std::filesystem::path & path)"

.PP
Load configuration from a given file\&. 
.PP
\fBParameters:\fP
.RS 4
\fIpath\fP Path to the configuration file\&. 
.RE
.PP

.PP
Definition at line 20 of file ServerConfig\&.cpp\&.
.SS "void ServerConfig::updateEnabledModulesList ()"

.PP
Update list of enabled modules\&. 
.PP
Definition at line 36 of file ServerConfig\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Zia from the source code\&.
