.TH "Zia::Server" 3 "Sat Feb 29 2020" "Version 1.0" "Zia" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Zia::Server \- \fBServer\fP class to manage the server\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Server\&.hpp>\fP
.PP
Inherits Pipeline\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "using \fBConfigPtr\fP = std::shared_ptr< \fBServerConfig\fP >"
.br
.ti -1c
.RI "using \fBio_service\fP = boost::asio::io_service"
.br
.ti -1c
.RI "using \fBAcceptor\fP = boost::asio::ip::tcp::acceptor"
.br
.ti -1c
.RI "using \fBSocket\fP = boost::asio::ip::tcp::socket"
.br
.ti -1c
.RI "using \fBEndpoint\fP = boost::asio::ip::tcp::endpoint"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBServer\fP (const \fBConfigPtr\fP &config)"
.br
.ti -1c
.RI "void \fBrun\fP ()"
.br
.RI "Run \fBServer\fP\&. "
.ti -1c
.RI "void \fBclose\fP ()"
.br
.RI "Close \fBServer\fP\&. "
.in -1c
.SH "Detailed Description"
.PP 
\fBServer\fP class to manage the server\&. 
.PP
Definition at line 22 of file Server\&.hpp\&.
.SH "Member Typedef Documentation"
.PP 
.SS "using \fBZia::Server::Acceptor\fP =  boost::asio::ip::tcp::acceptor"

.PP
Definition at line 29 of file Server\&.hpp\&.
.SS "using \fBZia::Server::ConfigPtr\fP =  std::shared_ptr<\fBServerConfig\fP>"

.PP
Definition at line 25 of file Server\&.hpp\&.
.SS "using \fBZia::Server::Endpoint\fP =  boost::asio::ip::tcp::endpoint"

.PP
Definition at line 33 of file Server\&.hpp\&.
.SS "using \fBZia::Server::io_service\fP =  boost::asio::io_service"

.PP
Definition at line 27 of file Server\&.hpp\&.
.SS "using \fBZia::Server::Socket\fP =  boost::asio::ip::tcp::socket"

.PP
Definition at line 31 of file Server\&.hpp\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Server::Server (const \fBConfigPtr\fP & config)"

.PP
Definition at line 17 of file Server\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "void Server::close ()"

.PP
Close \fBServer\fP\&. 
.PP
Definition at line 61 of file Server\&.cpp\&.
.SS "void Server::run ()"

.PP
Run \fBServer\fP\&. 
.PP
Definition at line 56 of file Server\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Zia from the source code\&.
