.TH "Zia::Log" 3 "Sat Feb 29 2020" "Version 1.0" "Zia" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Zia::Log \- \fBLog\fP class to manage the log\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Log\&.hpp>\fP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBsetPathFile\fP (const std::string &) noexcept"
.br
.ti -1c
.RI "static void \fBinfo\fP (const std::string &msg, bool writeInFile=false) noexcept"
.br
.ti -1c
.RI "static void \fBwarning\fP (const std::string &msg, bool writeInFile=false) noexcept"
.br
.ti -1c
.RI "static void \fBcritical\fP (const std::string &msg, bool writeInFile=false) noexcept"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static long \fBNumbersInfo\fP = 0"
.br
.ti -1c
.RI "static long \fBNumbersWarning\fP = 0"
.br
.ti -1c
.RI "static long \fBNumbersCritical\fP = 0"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBLog\fP class to manage the log\&. 
.PP
Definition at line 20 of file Log\&.hpp\&.
.SH "Member Function Documentation"
.PP 
.SS "void Zia::Log::critical (const std::string & msg, bool writeInFile = \fCfalse\fP)\fC [static]\fP, \fC [noexcept]\fP"

.PP
Definition at line 35 of file Log\&.cpp\&.
.SS "void Zia::Log::info (const std::string & msg, bool writeInFile = \fCfalse\fP)\fC [static]\fP, \fC [noexcept]\fP"

.PP
Definition at line 21 of file Log\&.cpp\&.
.SS "void Zia::Log::setPathFile (const std::string & path)\fC [static]\fP, \fC [noexcept]\fP"

.PP
Definition at line 16 of file Log\&.cpp\&.
.SS "void Zia::Log::warning (const std::string & msg, bool writeInFile = \fCfalse\fP)\fC [static]\fP, \fC [noexcept]\fP"

.PP
Definition at line 28 of file Log\&.cpp\&.
.SH "Member Data Documentation"
.PP 
.SS "long Zia::Log::NumbersCritical = 0\fC [static]\fP"

.PP
Definition at line 30 of file Log\&.hpp\&.
.SS "long Zia::Log::NumbersInfo = 0\fC [static]\fP"

.PP
Definition at line 28 of file Log\&.hpp\&.
.SS "long Zia::Log::NumbersWarning = 0\fC [static]\fP"

.PP
Definition at line 29 of file Log\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Zia from the source code\&.
