.TH "Zia::Connection" 3 "Sat Feb 29 2020" "Version 1.0" "Zia" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Zia::Connection \- \fBConnection\fP class to manage the connection\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Connection\&.hpp>\fP
.PP
Inherits enable_shared_from_this< Zia::Connection >\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "using \fBsocket\fP = boost::asio::ip::tcp::socket"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBConnection\fP (void)=delete"
.br
.RI "Contructor of the \fBConnection\fP class\&. "
.ti -1c
.RI "\fBConnection\fP (\fBsocket\fP sock, \fBConnectionManager\fP &connectionManager, oZ::Pipeline &pipeline, bool encryption=false)"
.br
.RI "Contructor of the \fBConnection\fP class\&. "
.ti -1c
.RI "void \fBstart\fP (void)"
.br
.RI "Start the connection between browser and serv (client) "
.ti -1c
.RI "void \fBstop\fP (void)"
.br
.RI "Stop the connection between browser and serv (client) "
.in -1c
.SH "Detailed Description"
.PP 
\fBConnection\fP class to manage the connection\&. 
.PP
Definition at line 25 of file Connection\&.hpp\&.
.SH "Member Typedef Documentation"
.PP 
.SS "using \fBZia::Connection::socket\fP =  boost::asio::ip::tcp::socket"

.PP
Definition at line 28 of file Connection\&.hpp\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Zia::Connection::Connection (void)\fC [delete]\fP"

.PP
Contructor of the \fBConnection\fP class\&. 
.SS "Zia::Connection::Connection (\fBsocket\fP sock, \fBConnectionManager\fP & connectionManager, oZ::Pipeline & pipeline, bool encryption = \fCfalse\fP)"

.PP
Contructor of the \fBConnection\fP class\&. 
.PP
\fBParameters:\fP
.RS 4
\fIsock\fP Socket accepted by the serveur 
.br
\fIconnectionManager\fP \fBConnection\fP manager of the server 
.br
\fIpipeline\fP \fBServer\fP's pipeline use for modif the context 
.br
\fIencryption\fP Bool use to know if this will be in https or not 
.RE
.PP

.PP
Definition at line 17 of file Connection\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "void Zia::Connection::start (void)"

.PP
Start the connection between browser and serv (client) 
.PP
Definition at line 26 of file Connection\&.cpp\&.
.SS "void Zia::Connection::stop (void)"

.PP
Stop the connection between browser and serv (client) 
.PP
Definition at line 139 of file Connection\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Zia from the source code\&.
