.TH "Zia::ConnectionManager" 3 "Sat Feb 29 2020" "Version 1.0" "Zia" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Zia::ConnectionManager \- \fBConnectionManager\fP class to manage the connection\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ConnectionManager\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBConnectionManager\fP ()=default"
.br
.RI "Cronstructor for the connection manager\&. "
.ti -1c
.RI "void \fBaddClient\fP (\fBConnectionPtr\fP client)"
.br
.RI "Add a client give to the manager in the list\&. "
.ti -1c
.RI "void \fBeraseClient\fP (\fBConnectionPtr\fP client)"
.br
.RI "Remove a client give to the manager to the list\&. "
.ti -1c
.RI "void \fBeraseAll\fP (void)"
.br
.RI "Add a client give to the manager in the list\&. "
.in -1c
.SH "Detailed Description"
.PP 
\fBConnectionManager\fP class to manage the connection\&. 
.PP
Definition at line 24 of file ConnectionManager\&.hpp\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Zia::ConnectionManager::ConnectionManager ()\fC [default]\fP"

.PP
Cronstructor for the connection manager\&. 
.SH "Member Function Documentation"
.PP 
.SS "void Zia::ConnectionManager::addClient (\fBConnectionPtr\fP client)"

.PP
Add a client give to the manager in the list\&. 
.PP
\fBParameters:\fP
.RS 4
\fIclient\fP Pointer on the client 
.RE
.PP

.PP
Definition at line 11 of file ConnectionManager\&.cpp\&.
.SS "void Zia::ConnectionManager::eraseAll (void)"

.PP
Add a client give to the manager in the list\&. 
.PP
Definition at line 23 of file ConnectionManager\&.cpp\&.
.SS "void Zia::ConnectionManager::eraseClient (\fBConnectionPtr\fP client)"

.PP
Remove a client give to the manager to the list\&. 
.PP
\fBParameters:\fP
.RS 4
\fIclient\fP Pointer on the client 
.RE
.PP

.PP
Definition at line 17 of file ConnectionManager\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Zia from the source code\&.
