.TH "Zia::Module" 3 "Sat Feb 29 2020" "Version 1.0" "Zia" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Zia::Module \- \fBModule\fP class to manage the modules\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Module\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBModule\fP (const \fBcfg::FileDescriptor\fP &path)"
.br
.RI "Construct a new \fBModule\fP object\&. "
.ti -1c
.RI "\fB~Module\fP ()=default"
.br
.RI "Destroy the \fBModule\fP object\&. "
.ti -1c
.RI "const std::string \fBgetName\fP () const noexcept"
.br
.RI "Get the module's name\&. "
.ti -1c
.RI "const std::string \fBgetName\fP (const \fBcfg::FileDescriptor\fP &file) const"
.br
.RI "Generate the module's name from a file descriptor\&. "
.ti -1c
.RI "const std::string \fBgetPath\fP () const noexcept"
.br
.RI "Get the module's library path\&. "
.in -1c
.SH "Detailed Description"
.PP 
\fBModule\fP class to manage the modules\&. 
.PP
Definition at line 17 of file Module\&.hpp\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Module::Module (const \fBcfg::FileDescriptor\fP & path)"

.PP
Construct a new \fBModule\fP object\&. 
.PP
\fBParameters:\fP
.RS 4
\fIpath\fP File descriptor of the module library\&. 
.RE
.PP

.PP
Definition at line 12 of file Module\&.cpp\&.
.SS "Zia::Module::~Module ()\fC [default]\fP"

.PP
Destroy the \fBModule\fP object\&. 
.SH "Member Function Documentation"
.PP 
.SS "const std::string Module::getName (void) const\fC [noexcept]\fP"

.PP
Get the module's name\&. 
.PP
\fBReturns:\fP
.RS 4
\fBModule\fP's name\&. 
.RE
.PP

.PP
Definition at line 18 of file Module\&.cpp\&.
.SS "const std::string Module::getName (const \fBcfg::FileDescriptor\fP & file) const"

.PP
Generate the module's name from a file descriptor\&. 
.PP
\fBReturns:\fP
.RS 4
Generated module name\&. 
.RE
.PP

.PP
Definition at line 23 of file Module\&.cpp\&.
.SS "const std::string Module::getPath () const\fC [noexcept]\fP"

.PP
Get the module's library path\&. 
.PP
\fBReturns:\fP
.RS 4
\fBModule\fP's library path\&. 
.RE
.PP

.PP
Definition at line 33 of file Module\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Zia from the source code\&.
